# Generated by Django 4.1.7 on 2023-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('L', 'Комната'), ('B', 'Комплекс')], max_length=1)),
            ],
        ),
    ]
